//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 
namespace Serilizer {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd", IsNullable=false)]
    internal partial class Project {
        
        private ProjectFonts fontsField;
        
        private ProjectFallbackFonts fallbackFontsField;
        
        private ProjectTemplate[] templatesField;
        
        private Language defaultLanguageField;
        
        /// <remarks/>
        internal ProjectFonts Fonts {
            get {
                return this.fontsField;
            }
            set {
                this.fontsField = value;
            }
        }
        
        /// <remarks/>
        internal ProjectFallbackFonts FallbackFonts {
            get {
                return this.fallbackFontsField;
            }
            set {
                this.fallbackFontsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Template", IsNullable=false)]
        internal ProjectTemplate[] Templates {
            get {
                return this.templatesField;
            }
            set {
                this.templatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal Language DefaultLanguage {
            get {
                return this.defaultLanguageField;
            }
            set {
                this.defaultLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class ProjectFonts {
        
        private ProjectFontsFont[] fontField;
        
        private bool useSystemFallbackField;
        
        private string defaultFontField;
        
        internal ProjectFonts() {
            this.useSystemFallbackField = true;
            this.defaultFontField = "Verdana";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Font")]
        internal ProjectFontsFont[] Font {
            get {
                return this.fontField;
            }
            set {
                this.fontField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        internal bool UseSystemFallback {
            get {
                return this.useSystemFallbackField;
            }
            set {
                this.useSystemFallbackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Verdana")]
        internal string DefaultFont {
            get {
                return this.defaultFontField;
            }
            set {
                this.defaultFontField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class ProjectFontsFont {
        
        private FontLocation regularField;
        
        private FontLocation italicField;
        
        private FontLocation boldField;
        
        private FontLocation boldItalicField;
        
        private string familyNameField;
        
        /// <remarks/>
        internal FontLocation Regular {
            get {
                return this.regularField;
            }
            set {
                this.regularField = value;
            }
        }
        
        /// <remarks/>
        internal FontLocation Italic {
            get {
                return this.italicField;
            }
            set {
                this.italicField = value;
            }
        }
        
        /// <remarks/>
        internal FontLocation Bold {
            get {
                return this.boldField;
            }
            set {
                this.boldField = value;
            }
        }
        
        /// <remarks/>
        internal FontLocation BoldItalic {
            get {
                return this.boldItalicField;
            }
            set {
                this.boldItalicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string FamilyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class FontLocation {
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class Fill {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal abstract partial class Run {
        
        private FontStyle fontStyleField;
        
        private bool fontStyleFieldSpecified;
        
        private double emSizeField;
        
        private bool emSizeFieldSpecified;
        
        private string fontNameField;
        
        private string colorField;
        
        private Language languageField;
        
        private bool languageFieldSpecified;
        
        private bool isVisibleField;
        
        private string isVisiblePathField;
        
        internal Run() {
            this.isVisibleField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal FontStyle FontStyle {
            get {
                return this.fontStyleField;
            }
            set {
                this.fontStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        internal bool FontStyleSpecified {
            get {
                return this.fontStyleFieldSpecified;
            }
            set {
                this.fontStyleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal double EmSize {
            get {
                return this.emSizeField;
            }
            set {
                this.emSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        internal bool EmSizeSpecified {
            get {
                return this.emSizeFieldSpecified;
            }
            set {
                this.emSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string FontName {
            get {
                return this.fontNameField;
            }
            set {
                this.fontNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal Language Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        internal bool LanguageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        internal bool IsVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string IsVisiblePath {
            get {
                return this.isVisiblePathField;
            }
            set {
                this.isVisiblePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal enum FontStyle {
        
        /// <remarks/>
        Regular,
        
        /// <remarks/>
        Bold,
        
        /// <remarks/>
        Italic,
        
        /// <remarks/>
        BoldItalic,
        
        /// <remarks/>
        Underline,
        
        /// <remarks/>
        Strikeout,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal enum Language {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("de-DE")]
        deDE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("en-US")]
        enUS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("en-GB")]
        enGB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ru-RU")]
        ruRU,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForeEachParagraph))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal abstract partial class AbstractParagraph {
        
        private bool isVisibleField;
        
        private string isVisiblePathField;
        
        internal AbstractParagraph() {
            this.isVisibleField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        internal bool IsVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string IsVisiblePath {
            get {
                return this.isVisiblePathField;
            }
            set {
                this.isVisiblePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class ForeEachParagraph : AbstractParagraph {
        
        private AbstractParagraph[] itemsField;
        
        private string selectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ForEach", typeof(ForeEachParagraph))]
        [System.Xml.Serialization.XmlElementAttribute("Paragraph", typeof(Paragraph))]
        internal AbstractParagraph[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Select {
            get {
                return this.selectField;
            }
            set {
                this.selectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd", IsNullable=false)]
    internal partial class Paragraph : AbstractParagraph {
        
        private Run[] itemsField;
        
        private FontStyle fontStyleField;
        
        private double emSizeField;
        
        private string fontNameField;
        
        private string colorField;
        
        private Language languageField;
        
        private bool languageFieldSpecified;
        
        private double linespacingField;
        
        private string beforeParagraphField;
        
        private string afterParagraphField;
        
        private Alignment alignmentField;
        
        internal Paragraph() {
            this.fontStyleField = FontStyle.Regular;
            this.emSizeField = 12D;
            this.colorField = "Black";
            this.linespacingField = 1D;
            this.beforeParagraphField = "0 mm";
            this.afterParagraphField = "0 mm";
            this.alignmentField = Alignment.Near;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ForEachRun", typeof(ForEachRun))]
        [System.Xml.Serialization.XmlElementAttribute("LineBreak", typeof(LineBreak))]
        [System.Xml.Serialization.XmlElementAttribute("TextRun", typeof(TextRun))]
        internal Run[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FontStyle.Regular)]
        internal FontStyle FontStyle {
            get {
                return this.fontStyleField;
            }
            set {
                this.fontStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(12D)]
        internal double EmSize {
            get {
                return this.emSizeField;
            }
            set {
                this.emSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string FontName {
            get {
                return this.fontNameField;
            }
            set {
                this.fontNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Black")]
        internal string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal Language Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        internal bool LanguageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        internal double Linespacing {
            get {
                return this.linespacingField;
            }
            set {
                this.linespacingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0 mm")]
        internal string BeforeParagraph {
            get {
                return this.beforeParagraphField;
            }
            set {
                this.beforeParagraphField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0 mm")]
        internal string AfterParagraph {
            get {
                return this.afterParagraphField;
            }
            set {
                this.afterParagraphField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(Alignment.Near)]
        internal Alignment Alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd", IsNullable=false)]
    internal partial class ForEachRun : Run {
        
        private Run[] itemsField;
        
        private string selectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ForEachRun", typeof(ForEachRun))]
        [System.Xml.Serialization.XmlElementAttribute("LineBreak", typeof(LineBreak))]
        [System.Xml.Serialization.XmlElementAttribute("TextRun", typeof(TextRun))]
        internal Run[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Select {
            get {
                return this.selectField;
            }
            set {
                this.selectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd", IsNullable=false)]
    internal partial class LineBreak : Run {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd", IsNullable=false)]
    internal partial class TextRun : Run {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Text", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("TextPath", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        internal string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        internal ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd", IncludeInSchema=false)]
    internal enum ItemChoiceType {
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        TextPath,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal enum Alignment {
        
        /// <remarks/>
        Near,
        
        /// <remarks/>
        Center,
        
        /// <remarks/>
        Far,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImageElement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RectElement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextElement))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal abstract partial class BaseElement {
        
        private string leftField;
        
        private string topField;
        
        private string widthField;
        
        private string heightField;
        
        private float rotationField;
        
        private float rotationOriginXField;
        
        private float rotationOriginYField;
        
        private bool isVisibleField;
        
        private string isVisiblePathField;
        
        private double zPositionField;
        
        internal BaseElement() {
            this.rotationField = ((float)(0F));
            this.rotationOriginXField = ((float)(0F));
            this.rotationOriginYField = ((float)(0F));
            this.isVisibleField = true;
            this.zPositionField = 0D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        internal float rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        internal float rotationOriginX {
            get {
                return this.rotationOriginXField;
            }
            set {
                this.rotationOriginXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        internal float rotationOriginY {
            get {
                return this.rotationOriginYField;
            }
            set {
                this.rotationOriginYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        internal bool IsVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string IsVisiblePath {
            get {
                return this.isVisiblePathField;
            }
            set {
                this.isVisiblePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        internal double ZPosition {
            get {
                return this.zPositionField;
            }
            set {
                this.zPositionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class ImageElement : BaseElement {
        
        private string imageLocationPathField;
        
        private string imageLocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string ImageLocationPath {
            get {
                return this.imageLocationPathField;
            }
            set {
                this.imageLocationPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string ImageLocation {
            get {
                return this.imageLocationField;
            }
            set {
                this.imageLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class RectElement : BaseElement {
        
        private RectElementBorder borderField;
        
        private RectElementFill fillField;
        
        /// <remarks/>
        internal RectElementBorder Border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
            }
        }
        
        /// <remarks/>
        internal RectElementFill Fill {
            get {
                return this.fillField;
            }
            set {
                this.fillField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class RectElementBorder {
        
        private string colorField;
        
        private double thiknessField;
        
        internal RectElementBorder() {
            this.thiknessField = 1D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        internal double Thikness {
            get {
                return this.thiknessField;
            }
            set {
                this.thiknessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class RectElementFill {
        
        private Fill itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GradientFill", typeof(GradientFill))]
        [System.Xml.Serialization.XmlElementAttribute("SolidFill", typeof(SolidFill))]
        internal Fill Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd", IsNullable=false)]
    internal partial class GradientFill : Fill {
        
        private GradientFillPoint[] pointField;
        
        private string color1Field;
        
        private string color2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Point")]
        internal GradientFillPoint[] Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Color1 {
            get {
                return this.color1Field;
            }
            set {
                this.color1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Color2 {
            get {
                return this.color2Field;
            }
            set {
                this.color2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class GradientFillPoint {
        
        private double xField;
        
        private double yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal double X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal double Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd", IsNullable=false)]
    internal partial class SolidFill : Fill {
        
        private string colorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class TextElement : BaseElement {
        
        private AbstractParagraph[] itemsField;
        
        private double minEmSizeScaleField;
        
        private double maxEmSizeScaleField;
        
        private Alignment verticalAlignmentField;
        
        internal TextElement() {
            this.minEmSizeScaleField = 1D;
            this.maxEmSizeScaleField = 1D;
            this.verticalAlignmentField = Alignment.Near;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ForEach", typeof(ForeEachParagraph))]
        [System.Xml.Serialization.XmlElementAttribute("Paragraph", typeof(Paragraph))]
        internal AbstractParagraph[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        internal double MinEmSizeScale {
            get {
                return this.minEmSizeScaleField;
            }
            set {
                this.minEmSizeScaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        internal double MaxEmSizeScale {
            get {
                return this.maxEmSizeScaleField;
            }
            set {
                this.maxEmSizeScaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(Alignment.Near)]
        internal Alignment VerticalAlignment {
            get {
                return this.verticalAlignmentField;
            }
            set {
                this.verticalAlignmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class ProjectFallbackFonts {
        
        private ProjectFallbackFontsFont[] fontField;
        
        private ProjectFallbackFontsNotFoundCharacter notFoundCharacterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Font")]
        internal ProjectFallbackFontsFont[] Font {
            get {
                return this.fontField;
            }
            set {
                this.fontField = value;
            }
        }
        
        /// <remarks/>
        internal ProjectFallbackFontsNotFoundCharacter NotFoundCharacter {
            get {
                return this.notFoundCharacterField;
            }
            set {
                this.notFoundCharacterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class ProjectFallbackFontsFont {
        
        private string familyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string FamilyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class ProjectFallbackFontsNotFoundCharacter {
        
        private string familyNameField;
        
        private string substituteCharacterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string FamilyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string SubstituteCharacter {
            get {
                return this.substituteCharacterField;
            }
            set {
                this.substituteCharacterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://raw.githubusercontent.com/LokiMidgard/PdfCardGenerator/master/PdfCardGene" +
        "rator/XMLImport.xsd")]
    internal partial class ProjectTemplate {
        
        private BaseElement[] itemsField;
        
        private string contextField;
        
        private string widthField;
        
        private string heightField;
        
        private string xsltField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Image", typeof(ImageElement))]
        [System.Xml.Serialization.XmlElementAttribute("Rect", typeof(RectElement))]
        [System.Xml.Serialization.XmlElementAttribute("Text", typeof(TextElement))]
        internal BaseElement[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        internal string Xslt {
            get {
                return this.xsltField;
            }
            set {
                this.xsltField = value;
            }
        }
    }
}
